name: pam_sbd_final
description: Aplikasi Lost and Found Kampus

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.2
  image_picker: ^1.0.7
  path: ^1.9.0
  mime: ^1.0.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Registrasi Aset
  assets:
    # Mendaftarkan seluruh folder images
    # Pastikan file logo.png ada di dalam folder: assets/images/
    - assets/images/
    
    # Jika Anda punya folder icons untuk aset lain, daftarkan juga (opsional)
    # - assets/icons/

# Konfigurasi Icon Launcher (Icon Aplikasi di Menu HP)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # Pastikan file ini ada: assets/icons/logo_icon.png
  image_path: "assets/icons/logo_icon.png"
  min_sdk_android: 21